'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import { AuthGuard } from '@/components/auth/AuthGuard';
import { Navbar } from '@/components/layout/Navbar';
import { auth } from '@/lib/firebase/client';
import type { GuardianConnection } from '@/lib/types';

function StudentGuardianSettings() {
  const [connections, setConnections] = useState<GuardianConnection[]>([]); const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [relationship, setRelationship] = useState(''); const [location, setLocation] = useState(false); const [message, setMessage] = useState('');
  async function api(body?: object) { const token = await auth.currentUser?.getIdToken(); const res = await fetch('/api/guardian', { method: body ? 'POST' : 'GET', headers: { ...(body ? { 'Content-Type': 'application/json' } : {}), Authorization: `Bearer ${token || ''}` }, ...(body ? { body: JSON.stringify(body) } : {}) }); return { res, data: await res.json() }; }
  async function load() { const { res, data } = await api(); if (res.ok) setConnections(data.connections); }
  useEffect(() => { void load(); }, []);
  async function invite(event: FormEvent) { event.preventDefault(); setMessage(''); const { res, data } = await api({ action: 'invite', name, phone, relationship }); if (!res.ok) { setMessage(data.error); return; } setName(''); setPhone(''); setRelationship(''); setMessage('Guardian invitation created. Ask them to open Guardian Login and verify this phone number.'); await load(); }
  async function confirm(connectionId: string) { const { res, data } = await api({ action: 'confirm', connectionId, permissions: { emergencyAlerts: true, emergencyLocation: location } }); setMessage(res.ok ? 'Guardian connected. Only emergency information will be shared.' : data.error); await load(); }
  return <main className="mx-auto max-w-4xl px-5 py-10"><section className="rounded-[2rem] bg-slate-950 p-7 text-white"><ShieldCheck className="text-cyan-300" size={30} /><h1 className="mt-3 font-display text-3xl font-semibold">Guardian & privacy</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-indigo-100">Trusted Guardians can receive an emergency alert only after you confirm their connection. They never receive your tutor chats, counselling messages, memories, or academic history.</p></section><section className="glass-card mt-7 rounded-3xl p-6"><h2 className="font-display text-xl font-semibold">Add a Guardian</h2><form onSubmit={invite} className="mt-5 grid gap-4 sm:grid-cols-3"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Guardian name" className="aurora-input" required /><input value={relationship} onChange={(e) => setRelationship(e.target.value)} placeholder="Relationship" className="aurora-input" required /><input value={phone} onChange={(e) => { setPhone(e.target.value); setMessage(''); }} placeholder="9876543210 or +919876543210" className="aurora-input" inputMode="tel" required /><label className="sm:col-span-3 flex items-center gap-2 text-sm text-ink/70"><input type="checkbox" checked={location} onChange={(e) => setLocation(e.target.checked)} /> Share location only during an activated emergency</label><button className="w-fit rounded-xl bg-indigo px-5 py-3 text-sm font-bold text-white">Send invitation</button></form>{message && <p className="mt-4 text-sm text-ink/70">{message}</p>}</section><section className="mt-7"><h2 className="font-display text-xl font-semibold">Your Guardian network</h2><div className="mt-4 grid gap-3">{connections.length === 0 ? <p className="rounded-2xl border border-dashed border-ink/20 p-5 text-sm text-ink/60">No Guardians yet.</p> : connections.map((connection) => <article key={connection.id} className="rounded-2xl border border-ink/10 bg-surface p-5"><div className="flex items-center justify-between gap-4"><div><p className="font-bold">{connection.guardianName}</p><p className="text-sm text-ink/60">{connection.relationship} · {connection.status.replace('_', ' ')}</p></div>{connection.status === 'ACCEPTED' && <button onClick={() => confirm(connection.id)} className="rounded-xl bg-indigo px-4 py-2 text-sm font-bold text-white">Confirm connection</button>}</div>{connection.status === 'ACTIVE' && <p className="mt-3 text-xs text-emerald-600">Emergency alerts: ON · Emergency location: {connection.permissions.emergencyLocation ? 'ON' : 'OFF'}</p>}</article>)}</div></section></main>;
}

export default function StudentGuardianPage() { return <AuthGuard allowedRoles={['student']}><Navbar /><StudentGuardianSettings /></AuthGuard>; }
