'use client';

import { AlertTriangle, Phone, ShieldAlert, X } from 'lucide-react';
import type { TrustedContact } from '@/lib/types';

export function CrisisSafetyModal({ contact, onClose }: { contact?: TrustedContact; onClose: () => void }) {
  const initials = contact?.name?.split(/\s+/).map((name) => name[0]).join('').slice(0, 2).toUpperCase() || '?';
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-ink/70 p-4" role="alertdialog" aria-modal="true" aria-labelledby="crisis-title">
    <div className="w-full max-w-md rounded-3xl bg-surface p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><span className="rounded-full bg-red-100 p-3 text-red-700"><ShieldAlert size={26} /></span><button onClick={onClose} aria-label="Close" className="rounded-full p-2 text-ink/60 hover:bg-mist"><X size={20} /></button></div><h1 id="crisis-title" className="mt-4 font-display text-2xl font-semibold">You don&apos;t have to handle this alone.</h1><p className="mt-2 text-sm leading-6 text-ink/70">Please contact someone who can be with you right now. If you or someone else may be in immediate danger, call emergency services now.</p>{contact && <a href={`tel:${contact.phone.replace(/[^+\d]/g, '')}`} className="mt-5 flex items-center gap-3 rounded-2xl border border-indigo/20 bg-indigo-50 p-4 text-left dark:bg-indigo-500/10"><span className="flex h-12 w-12 items-center justify-center overflow-hidden rounded-full bg-indigo font-semibold text-white">{contact.photoUrl ? <img src={contact.photoUrl} alt="" className="h-full w-full object-cover" /> : initials}</span><span className="min-w-0 flex-1"><span className="block text-xs font-medium text-indigo">Your trusted contact</span><strong className="block truncate">{contact.name}</strong><span className="block text-sm text-ink/60">{contact.phone}</span></span><Phone className="text-indigo" size={21} /></a>}<a href="tel:9152987821" className="mt-3 flex items-center gap-3 rounded-2xl border border-red-200 bg-red-50 p-4 text-left text-red-900"><AlertTriangle size={22} /><span className="flex-1"><strong className="block">Crisis support helpline</strong><span className="text-sm">Call 9152987821</span></span><Phone size={21} /></a><a href="tel:112" className="mt-3 flex items-center gap-3 rounded-2xl border border-ink/15 p-4 text-left"><Phone size={22} className="text-ink/70" /><span><strong className="block">Emergency services</strong><span className="text-sm text-ink/60">Call 112 if there is immediate danger.</span></span></a><p className="mt-4 text-xs leading-5 text-ink/50">VidyaAI cannot provide emergency help. Please make a call now or ask a nearby trusted person to stay with you.</p></div>
  </div>;
}
